"""add language to posts

Revision ID: 470d6b80c94a
Revises: 93f3e79730c1
Create Date: 2019-10-30 20:58:04.627713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470d6b80c94a'
down_revision = '93f3e79730c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
