"""add post fields

Revision ID: 5c5168f512ef
Revises: 470d6b80c94a
Create Date: 2019-11-05 16:48:20.967012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5168f512ef'
down_revision = '470d6b80c94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('public', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'upvotes')
    op.drop_column('post', 'public')
    op.drop_column('post', 'downvotes')
    # ### end Alembic commands ###
