"""add post fields 2

Revision ID: f632f44e6f8a
Revises: 5c5168f512ef
Create Date: 2019-11-05 16:49:13.301987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f632f44e6f8a'
down_revision = '5c5168f512ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('visible', sa.Boolean(), nullable=True))
    op.drop_column('post', 'public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('public', sa.BOOLEAN(), nullable=True))
    op.drop_column('post', 'visible')
    # ### end Alembic commands ###
